### ISSUE TITLE
Removing a filter field from the UI should remove the filter

### ISSUE THREAD

**Issue by gmaclennan** [digidem/react-mapfilter#62]
Expected behaviour:

When you open the settings "Change Filter" and turn off a filter for a field, it should be removed from the UI, and any filters that were set for that field should be removed.

Actual behaviour:

Turning off a field with filters set in the filter settings does not remove it from the UI. After turning it off once all the filters are removed it magically disappears.

Possible solution:

Use the UPDATE_FILTER action to reset filters for a field that is removed from the UI.

**Comment by okdistribute** [comment]
Can't reproduce, I think this was fixed by @mojodna
