### ISSUE TITLE
Controllable Map Properties

### ISSUE THREAD

**Issue by GoGoCarl** [digidem/react-mapfilter#70]
Feature Request:

Allow the following map properties to be controlled (i.e. being able to supply initial values for these and subscribe to the map to listen for changes to these properties)

* Map Center Point (lat/lng) (listen for move changes)
* Map Zoom (listen for zoom changes)

This is critical for users where a small set of custom tiles is being used and not all zoom levels are provided with the tile set.

**Comment by gmaclennan** [comment]
@GoGoCarl currently when the data is updated (e.g. any feature is added/modified/deleted) then the map zoom and center will update to show all the data points in the map extent. This will currently happen even if we make this a controllable prop (well `onChangeMapView` would be called with the new values to fit the bounds of the data).

Is this what we want or would it work exposing `maxBounds` and `minZoom` and `maxZoom` properties that would limit map zoom/panning?

**Comment by GoGoCarl** [comment]
I see. So there is no explicit control over centered the map at a coordinate, ignoring the data set itself, right? I think that might be fine, though I'm guessing it may be useful to have a "default" area in cases where there are no points on the map.

Regarding zoom, I would want to set/get the `current` zoom level, as opposed to `minZoom`/`maxZoom`. I don't intend to restrict how much they zoom in or out, I'd just want to start users at a particular zoom level and, when they zoom in or out, track that current zoom level (using `onChangeMapView`).

**Comment by gmaclennan** [comment]
The idea of a default area makes sense. Do you think it would be useful to expose some `initial` props, as an alternative to making props controllable (and needing to listen with `onChange`)? It's relatively simple to just expose the map zoom and map center as a controllable prop, it's just a whitelist right now of props which map to the keys in the state.

**Comment by GoGoCarl** [comment]
Gotcha, yes, if zoom and center could be added to the whitelist, that would be great. For my particular use case, this is a bit extra/inefficient, since I don't need to track every time the center and zoom changes, I really just need to get the state at a given point in time (when the user clicks the Save button). But I can't think of any other way to get those values. With the `initial` props, that would work if there were a way to access those values by function call; maybe there's access to a ref to the map state? If you have other ideas, I'm open. But I would imagine whitelisting would be the most straightforward implementation.

**Comment by okdistribute** [comment]
Hi @GoGoCarl, I'll be working on the issues you opened now.

I just added mapPosition to the controllable props for the MapView object in this commit: https://github.com/digidem/react-mapfilter/commit/283aa4370a08470f8a7545c9c5e2475883082546

You can add `onChangeMapPosition={handleMapPosition}` to the `MapFilter` node in order to handle the map position.

Here's an example where `handleMapPosition` just prints out the results object, which containts `zoom`, `center`, and `bearing`:
https://www.dropbox.com/s/0gj3m54xx2br2gg/simple-console.mov?dl=0

**Comment by GoGoCarl** [comment]
@karissa This seems to cause an infinite loop somewhere when I add in `onChangeMapPosition`. Setting the `mapPosition` seems to work just fine, though.

**Comment by okdistribute** [comment]
What is your handleMapPosition function doing?

**Comment by GoGoCarl** [comment]
@karissa Just updating the state:

```
handleChangeMapPosition = mapPosition => {
    this.setState({ mapPosition: mapPosition })
  }
```

**Comment by okdistribute** [comment]
Ah I guess you shouldn't do that in this case, because the map is telling you when the position has changed and the changes were already reflected in the UI.

**Comment by GoGoCarl** [comment]
Ok, so this works slightly differently than the others. It makes sense though.

So, it sounds like the proper setup for this instead would be something like:

```
<MapFilter
  ...
  mapPosition={this.state.initialMapPosition}
  onChangeMapPosition={this.handleChangeMapPosition}
/>
```

Where `handleChangeMapPosition` is the same as the previous comment. If that's wrong, let me know.

Thanks!

**Comment by okdistribute** [comment]
Yeah, I guess if we wanted to make it work the same as the other `onChange` functions we'd need to catch the drag event and prevent MapBox from moving the map, but I think that would be a bit strange to handle manually.
