### ISSUE TITLE
Quit program when close the window

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/react-mapfilter#77]
On the Mac version:
At the moment if you close the Tizii Tizii window, the application stays open, and you have to quit it again in order for it to fully close and then be able to reopen it with the data. It would seem to make more sense to the user if when you closed the window the whole thing quit (like Mapeo does).

**Comment by okdistribute** [comment]
fixed in https://github.com/digidem/mapfilter-desktop/commit/66b8e139882d3a6cd99947f92de9807775843ae7
